version: "3" 
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dist:/var/lib/grafana/plugins/phalanx-grafana-datasource
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=admin

  phalanx:
    container_name: phalanx
    image: mosuka/phalanx:latest
    command:
      - '--host=phalanx'
      - '--bind-port=2000'
      - '--grpc-port=5000'
      - '--http-port=8000'
      - '--roles=indexer,searcher'
      - '--index-metastore-uri=file:///tmp/phalanx/metadata'
      - '--cors-allowed-methods=GET,POST,PUT,DELETE'
      - '--cors-allowed-origins=http://localhost:3000'
      - '--cors-allowed-headers=Content-Type'
      - '--log-level=info'
    ports:
      - "2000:2000"
      - "5000:5000"
      - "8000:8000"
    restart: always
